# -- Theme Options --
colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = false
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"
defaultSocialImage = ""
highlightCurrentMenuArea = false
smartTOC = false
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "custom"
  showRecent = false
  showRecentItems = 6
  showMoreLink = false
  showMoreLinkDest = "docs"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false
  disableHeroImageFilter = false
